name: ocr
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
 # image: ^3.0.1
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_face_detection: ^0.11.0
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  cupertino_icons: ^1.0.6
  flutter_vector_icons: ^2.0.0
  camera: ^0.11.0
  google_ml_kit: ^0.18.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
